owl_client:
  image: docker.burnish.cn/react:latest
  command: npm start
  volumes:
    - ./src:/code/src
    - ./webpack:/code/webpack
    - ./tests:/code/tests
    - ./package.json:/code/package.json
    - ./.babelrc:/code/.babelrc
    - ./.eslintrc:/code/.eslintrc
  ports:
    - "9000:9000"
